
DEADLOCKED_DREADZONE_ICON_URL = 'https://box.rac-horizon.com/downloads/dreadzone.png'
UYA_ICON_URL = None # 'https://box.rac-horizon.com/downloads/dreadzone.png'

DEADLOCKED_SKILLS_TABLE = [
  100,
  200,
  800,
  1600,
  2500,
  3500,
  5000,
  6500,
  8000,
  9500
]

StreamPhrases = [
  "I've seen baby tyhrranoids with better sniping skills than you.",
  "This sissy ninny just went live, watching them struggle should be fun!"
]

StatsPhrases = [
  "Listen up, you lardballs! These stats are the most pathetic display of skill level I have ever seen in {STATNAME}!"
]


WeaponSlotIds = {
  0: 'Wrench',
  1: 'Dual Vipers',
  2: 'Magma Cannon',
  3: 'Arbiter',
  4: 'Fusion Rifle',
  5: 'Mine Launcher',
  6: 'B6 Obliterator',
  7: 'Flail',
  8: 'Omnishield',
}

TeamIds = {
  0: 'Blue',
  1: 'Red',
  2: 'Green',
  3: 'Orange',
  4: 'Yellow',
  5: 'Purple',
  6: 'Aqua',
  7: 'Pink',
  8: 'Olive',
  9: 'Maroon'
}

SkinIds = {
  0: 'Ratchet',
  1: 'Battlebot',
  2: 'Dreadbot',
  3: 'Eviscerator',
  4: 'Shellshock',
  5: 'Squidzor',
  6: 'The Muscle',
  7: 'Mr. Sunshine',
  8: 'Venus',
  9: 'Ace',
  10: 'Reaper',
  11: 'Kid Nova',
  12: 'Starshield',
  13: 'King Claude',
  14: 'Thriller',
  15: 'Alpha Clank',
  16: 'W3RM',
  17: 'Landshark',
  18: 'Vernon',
  19: 'Jak',
  20: 'Renegade',
  21: 'Eugene',
}

AlphaModIds = {
  0: 'None',
  1: 'Speed',
  2: 'Ammo',
  3: 'Aiming',
  4: 'Impact',
  5: 'Area',
  6: 'Xp',
  7: 'Jackpot',
  8: 'Nanoleech'
}

ACCOUNT_STAT_OVERALL_RANK = 2
ACCOUNT_STAT_WINS = 3
ACCOUNT_STAT_LOSSES = 4
ACCOUNT_STAT_DISCONNECTS = 5
ACCOUNT_STAT_KILLS = 6
ACCOUNT_STAT_DEATHS = 7
ACCOUNT_STAT_GAMES_PLAYED = 8
ACCOUNT_STAT_DEATHMATCH_RANK = 11
ACCOUNT_STAT_DEATHMATCH_WINS = 12
ACCOUNT_STAT_DEATHMATCH_LOSSES = 13
ACCOUNT_STAT_DEATHMATCH_KILLS = 15
ACCOUNT_STAT_DEATHMATCH_DEATHS = 16
ACCOUNT_STAT_CONQUEST_RANK = 17
ACCOUNT_STAT_CONQUEST_WINS = 18
ACCOUNT_STAT_CONQUEST_LOSSES = 19
ACCOUNT_STAT_CONQUEST_KILLS = 21
ACCOUNT_STAT_CONQUEST_DEATHS = 22
ACCOUNT_STAT_CONQUEST_NODES_TAKEN = 23
ACCOUNT_STAT_CTF_RANK = 24
ACCOUNT_STAT_CTF_WINS = 25
ACCOUNT_STAT_CTF_LOSSES = 26
ACCOUNT_STAT_CTF_KILLS = 28
ACCOUNT_STAT_CTF_DEATHS = 29
ACCOUNT_STAT_CTF_FLAGS_CAPTURED = 30
ACCOUNT_STAT_KOTH_RANK = 31
ACCOUNT_STAT_KOTH_WINS = 32
ACCOUNT_STAT_KOTH_LOSSES = 33
ACCOUNT_STAT_KOTH_KILLS = 35
ACCOUNT_STAT_KOTH_DEATHS = 36
ACCOUNT_STAT_KOTH_TIME = 37
ACCOUNT_STAT_JUGGERNAUT_RANK = 38
ACCOUNT_STAT_JUGGERNAUT_WINS = 39
ACCOUNT_STAT_JUGGERNAUT_LOSSES = 40
ACCOUNT_STAT_JUGGERNAUT_KILLS = 42
ACCOUNT_STAT_JUGGERNAUT_DEATHS = 43
ACCOUNT_STAT_JUGGERNAUT_TIME = 44
ACCOUNT_STAT_WRENCH_KILLS = 45
ACCOUNT_STAT_WRENCH_DEATHS = 46
ACCOUNT_STAT_DUAL_VIPER_KILLS = 48
ACCOUNT_STAT_DUAL_VIPER_DEATHS = 49
ACCOUNT_STAT_MAGMA_CANNON_KILLS = 51
ACCOUNT_STAT_MAGMA_CANNON_DEATHS = 52
ACCOUNT_STAT_ARBITER_KILLS = 54
ACCOUNT_STAT_ARBITER_DEATHS = 55
ACCOUNT_STAT_FUSION_RIFLE_KILLS = 57
ACCOUNT_STAT_FUSION_RIFLE_DEATHS = 58
ACCOUNT_STAT_HUNTER_MINE_KILLS = 60
ACCOUNT_STAT_HUNTER_MINE_DEATHS = 61
ACCOUNT_STAT_B6_OBLITERATOR_KILLS = 63
ACCOUNT_STAT_B6_OBLITERATOR_DEATHS = 64
ACCOUNT_STAT_SCORPION_FLAIL_KILLS = 66
ACCOUNT_STAT_SCORPION_FLAIL_DEATHS = 67
ACCOUNT_STAT_ROADKILLS = 70
ACCOUNT_STAT_VEHICLE_SQUATS = 71
ACCOUNT_STAT_SQUATS = 72
ACCOUNT_STAT_HOLOSHIELD_KILLS = 73
ACCOUNT_STAT_HOLOSHIELD_DEATHS = 74

CUSTOM_STAT_TOTAL_HORIZON_BOLTS = 0
CUSTOM_STAT_CURRENT_HORIZON_BOLTS = 1
CUSTOM_STAT_SND_RANK = 50
CUSTOM_STAT_SND_WINS = 51
CUSTOM_STAT_SND_LOSSES = 52
CUSTOM_STAT_SND_GAMES_PLAYED = 53
CUSTOM_STAT_SND_KILLS = 54
CUSTOM_STAT_SND_DEATHS = 55
CUSTOM_STAT_SND_PLANTS = 56
CUSTOM_STAT_SND_DEFUSES = 57
CUSTOM_STAT_SND_NINJA_DEFUSES = 58
CUSTOM_STAT_SND_WINS_ATTACKING = 59
CUSTOM_STAT_SND_WINS_DEFENDING = 60
CUSTOM_STAT_SND_TIME_PLAYED = 61
CUSTOM_STAT_PAYLOAD_RANK = 70
CUSTOM_STAT_PAYLOAD_WINS = 71
CUSTOM_STAT_PAYLOAD_LOSSES = 72
CUSTOM_STAT_PAYLOAD_GAMES_PLAYED = 73
CUSTOM_STAT_PAYLOAD_KILLS = 74
CUSTOM_STAT_PAYLOAD_DEATHS = 75
CUSTOM_STAT_PAYLOAD_POINTS = 76
CUSTOM_STAT_PAYLOAD_KILLS_WHILE_HOT = 77
CUSTOM_STAT_PAYLOAD_KILLS_ON_HOT = 78
CUSTOM_STAT_PAYLOAD_TIME_PLAYED = 79
CUSTOM_STAT_SPLEEF_RANK = 90
CUSTOM_STAT_SPLEEF_WINS = 91
CUSTOM_STAT_SPLEEF_LOSSES = 92
CUSTOM_STAT_SPLEEF_GAMES_PLAYED = 93
CUSTOM_STAT_SPLEEF_ROUNDS_PLAYED = 94
CUSTOM_STAT_SPLEEF_POINTS = 95
CUSTOM_STAT_SPLEEF_TIME_PLAYED = 96
CUSTOM_STAT_SPLEEF_BOXES_BROKEN = 97
CUSTOM_STAT_INFECTED_RANK = 110
CUSTOM_STAT_INFECTED_WINS = 111
CUSTOM_STAT_INFECTED_LOSSES = 112
CUSTOM_STAT_INFECTED_GAMES_PLAYED = 113
CUSTOM_STAT_INFECTED_KILLS = 114
CUSTOM_STAT_INFECTED_DEATHS = 115
CUSTOM_STAT_INFECTED_INFECTIONS = 116
CUSTOM_STAT_INFECTED_TIMES_INFECTED = 117
CUSTOM_STAT_INFECTED_TIME_PLAYED = 118
CUSTOM_STAT_INFECTED_WINS_AS_SURVIVOR = 119
CUSTOM_STAT_INFECTED_WINS_AS_FIRST_INFECTED = 120
CUSTOM_STAT_GUNGAME_RANK = 130
CUSTOM_STAT_GUNGAME_WINS = 131
CUSTOM_STAT_GUNGAME_LOSSES = 132
CUSTOM_STAT_GUNGAME_GAMES_PLAYED = 133
CUSTOM_STAT_GUNGAME_KILLS = 134
CUSTOM_STAT_GUNGAME_DEATHS = 135
CUSTOM_STAT_GUNGAME_DEMOTIONS = 136
CUSTOM_STAT_GUNGAME_TIMES_DEMOTED = 137
CUSTOM_STAT_GUNGAME_TIMES_PROMOTED = 138
CUSTOM_STAT_GUNGAME_TIME_PLAYED = 139
CUSTOM_STAT_CLIMBER_RANK = 150
CUSTOM_STAT_CLIMBER_WINS = 151
CUSTOM_STAT_CLIMBER_LOSSES = 152
CUSTOM_STAT_CLIMBER_GAMES_PLAYED = 153
CUSTOM_STAT_CLIMBER_HIGH_SCORE = 154
CUSTOM_STAT_CLIMBER_TIME_PLAYED = 155
CUSTOM_STAT_SURVIVAL_RANK = 170
CUSTOM_STAT_SURVIVAL_GAMES_PLAYED = 171
CUSTOM_STAT_SURVIVAL_TIME_PLAYED = 172
CUSTOM_STAT_SURVIVAL_KILLS = 173
CUSTOM_STAT_SURVIVAL_DEATHS = 174
CUSTOM_STAT_SURVIVAL_REVIVES = 175
CUSTOM_STAT_SURVIVAL_TIMES_REVIVED = 176
CUSTOM_STAT_SURVIVAL_MAP1_SOLO_HIGH_SCORE = 177
CUSTOM_STAT_SURVIVAL_MAP1_COOP_HIGH_SCORE = 178
CUSTOM_STAT_SURVIVAL_MAP2_SOLO_HIGH_SCORE = 179
CUSTOM_STAT_SURVIVAL_MAP2_COOP_HIGH_SCORE = 180
CUSTOM_STAT_SURVIVAL_MAP3_SOLO_HIGH_SCORE = 181
CUSTOM_STAT_SURVIVAL_MAP3_COOP_HIGH_SCORE = 195
CUSTOM_STAT_SURVIVAL_MAP4_SOLO_HIGH_SCORE = 191
CUSTOM_STAT_SURVIVAL_MAP4_COOP_HIGH_SCORE = 192
CUSTOM_STAT_SURVIVAL_WRENCH_KILLS = 182
CUSTOM_STAT_SURVIVAL_DUAL_VIPER_KILLS = 183
CUSTOM_STAT_SURVIVAL_MAGMA_CANNON_KILLS = 184
CUSTOM_STAT_SURVIVAL_ARBITER_KILLS = 185
CUSTOM_STAT_SURVIVAL_FUSION_RIFLE_KILLS = 186
CUSTOM_STAT_SURVIVAL_MINE_LAUNCHER_KILLS = 187
CUSTOM_STAT_SURVIVAL_B6_OBLITERATOR_KILLS = 188
CUSTOM_STAT_SURVIVAL_SCORPION_FLAIL_KILLS = 189
CUSTOM_STAT_SURVIVAL_MAP1_XP = 190
#CUSTOM_STAT_SURVIVAL_TIMES_ROLLED_MYSTERY_BOX = 191
#CUSTOM_STAT_SURVIVAL_TIMES_ACTIVATED_DEMON_BELL = 192
#CUSTOM_STAT_SURVIVAL_TIMES_ACTIVATED_POWER = 193
#CUSTOM_STAT_SURVIVAL_TOKENS_USED_ON_GATES = 194
CUSTOM_STAT_SURVIVAL_MAP1_PRESTIGE = 196
CUSTOM_STAT_SURVIVAL_MAP2_XP = 197
CUSTOM_STAT_SURVIVAL_MAP2_PRESTIGE = 198
CUSTOM_STAT_SURVIVAL_MAP3_XP = 199
CUSTOM_STAT_SURVIVAL_MAP3_PRESTIGE = 200
CUSTOM_STAT_SURVIVAL_MAP4_XP = 207
CUSTOM_STAT_SURVIVAL_MAP4_PRESTIGE = 208
CUSTOM_STAT_TRAINING_RANK = 210
CUSTOM_STAT_TRAINING_GAMES_PLAYED = 211
CUSTOM_STAT_TRAINING_TIME_PLAYED = 212
CUSTOM_STAT_TRAINING_TOTAL_KILLS = 213
CUSTOM_STAT_TRAINING_FUSION_BEST_POINTS = 214
CUSTOM_STAT_TRAINING_FUSION_BEST_TIME = 215
CUSTOM_STAT_TRAINING_FUSION_KILLS = 216
CUSTOM_STAT_TRAINING_FUSION_HITS = 217
CUSTOM_STAT_TRAINING_FUSION_MISSES = 218
CUSTOM_STAT_TRAINING_FUSION_ACCURACY = 219
CUSTOM_STAT_TRAINING_FUSION_BEST_COMBO = 220
CUSTOM_STAT_TRAINING_CYCLE_BEST_POINTS = 221
CUSTOM_STAT_TRAINING_CYCLE_BEST_COMBO = 222
CUSTOM_STAT_TRAINING_CYCLE_KILLS = 223
CUSTOM_STAT_TRAINING_CYCLE_DEATHS = 224
CUSTOM_STAT_TRAINING_CYCLE_FUSION_HITS = 225
CUSTOM_STAT_TRAINING_CYCLE_FUSION_MISSES = 226
CUSTOM_STAT_TRAINING_CYCLE_FUSION_ACCURACY = 227
